apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-app-deployment
  labels:
    app: wisecow
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: nainani344sumit/wisecow:latest
          ports:
            - containerPort: 4499