apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 8080      # Service Port
      targetPort: 4499 # Pod's containerPort
      nodePort: 30007  # Exposed on this port for external access
